# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_K <- function(K) {
    invisible(.Call('BWPMF_set_K', PACKAGE = 'BWPMF', K))
}

serialize_cookie <- function(Rpath = NULL) {
    .Call('BWPMF_serialize_cookie', PACKAGE = 'BWPMF', Rpath)
}

#'@export
deserialize_cookie.raw <- function(src) {
    invisible(.Call('BWPMF_deserialize_cookie_raw', PACKAGE = 'BWPMF', src))
}

#'@export
deserialize_cookie.character <- function(path) {
    invisible(.Call('BWPMF_deserialize_cookie_path', PACKAGE = 'BWPMF', path))
}

serialize_hostname <- function(Rpath = NULL) {
    .Call('BWPMF_serialize_hostname', PACKAGE = 'BWPMF', Rpath)
}

#'@export
deserialize_hostname.raw <- function(src) {
    invisible(.Call('BWPMF_deserialize_hostname_raw', PACKAGE = 'BWPMF', src))
}

#'@export
deserialize_hostname.character <- function(path) {
    invisible(.Call('BWPMF_deserialize_hostname_path', PACKAGE = 'BWPMF', path))
}

query_cookie <- function(cookie) {
    .Call('BWPMF_query_cookie', PACKAGE = 'BWPMF', cookie)
}

query_hostname <- function(hostname) {
    .Call('BWPMF_query_hostname', PACKAGE = 'BWPMF', hostname)
}

count_cookie <- function() {
    .Call('BWPMF_count_cookie', PACKAGE = 'BWPMF')
}

count_hostname <- function() {
    .Call('BWPMF_count_hostname', PACKAGE = 'BWPMF')
}

clean_cookie <- function() {
    invisible(.Call('BWPMF_clean_cookie', PACKAGE = 'BWPMF'))
}

clean_hostname <- function() {
    invisible(.Call('BWPMF_clean_hostname', PACKAGE = 'BWPMF'))
}

#'@title Encode the Source File for Calculating
#'@param x string. The path to the source file.
#'@param user_visit_lower_bound integer. If the user visit is less than 
#'   \code{user_visit_lower_bound}, then he/she will be filtered out.
#'@param progress numeric. The number of lines of the source file. If 
#'   the progress is set non-zero, then a progress bar will be displayed.
#'@param sep1 single character. The delimiter between the user and the rest.
#'@param sep2 single character. The delimiter between the pairs of item and the count.
#'@param sep3 single character. The delimiter between the item and count.
#'@export
encode.character <- function(x, user_visit_lower_bound = 0L, progress = 0, sep1 = "\1", sep2 = "\2", sep3 = "\3") {
    invisible(.Call('BWPMF_encode_character', PACKAGE = 'BWPMF', x, user_visit_lower_bound, progress, sep1, sep2, sep3))
}

#'@export
encode.data.frame <- function(x, user_index = 1L, item_index = 2L, progress = TRUE) {
    invisible(.Call('BWPMF_encode_data_frame', PACKAGE = 'BWPMF', x, user_index, item_index, progress))
}

#'@export
encode_data.character <- function(x, progress = 0, sep1 = "\1", sep2 = "\2", sep3 = "\3") {
    .Call('BWPMF_encode_data_character', PACKAGE = 'BWPMF', x, progress, sep1, sep2, sep3)
}

#'@export
encode_data.data.frame <- function(x, user_index = 1L, item_index = 2L, progress = TRUE) {
    .Call('BWPMF_encode_data_data_frame', PACKAGE = 'BWPMF', x, user_index, item_index, progress)
}

#'@export
serialize_history <- function(Rhistory, Rpath = NULL) {
    .Call('BWPMF_serialize_history', PACKAGE = 'BWPMF', Rhistory, Rpath)
}

#'@export
deserialize_history.raw <- function(src) {
    .Call('BWPMF_deserialize_history_raw', PACKAGE = 'BWPMF', src)
}

#'@export
deserialize_history.character <- function(path) {
    .Call('BWPMF_deserialize_history_path', PACKAGE = 'BWPMF', path)
}

#'@export
print.history <- function(Rhistory) {
    invisible(.Call('BWPMF_print_history', PACKAGE = 'BWPMF', Rhistory))
}

#'@export
check_history <- function(Rhistory) {
    .Call('BWPMF_check_history', PACKAGE = 'BWPMF', Rhistory)
}

#'@export
count_non_zero_of_history <- function(Rhistory) {
    .Call('BWPMF_count_non_zero_of_history', PACKAGE = 'BWPMF', Rhistory)
}

#'@export
count_cookie_history <- function(Rhistory) {
    .Call('BWPMF_count_cookie_history', PACKAGE = 'BWPMF', Rhistory)
}

#'@export
count_hostname_history <- function(Rhistory) {
    .Call('BWPMF_count_hostname_history', PACKAGE = 'BWPMF', Rhistory)
}

#'@export
extract_history <- function(Rhistory, id) {
    .Call('BWPMF_extract_history', PACKAGE = 'BWPMF', Rhistory, id)
}

test_list_of_list <- function() {
    invisible(.Call('BWPMF_test_list_of_list', PACKAGE = 'BWPMF'))
}

test_phi <- function(Rphi, Rhistory) {
    invisible(.Call('BWPMF_test_phi', PACKAGE = 'BWPMF', Rphi, Rhistory))
}

print_phi_index <- function(Rphi) {
    invisible(.Call('BWPMF_print_phi_index', PACKAGE = 'BWPMF', Rphi))
}

print_history_index <- function(Rhistory) {
    invisible(.Call('BWPMF_print_history_index', PACKAGE = 'BWPMF', Rhistory))
}

dump_phi <- function(Rphi) {
    .Call('BWPMF_dump_phi', PACKAGE = 'BWPMF', Rphi)
}

test_phi_on_disk <- function(path, value) {
    .Call('BWPMF_test_phi_on_disk', PACKAGE = 'BWPMF', path, value)
}

init_phi <- function(Rmodel, Rhistory, cached_file = "", cache_size = 10000L) {
    .Call('BWPMF_init_phi', PACKAGE = 'BWPMF', Rmodel, Rhistory, cached_file, cache_size)
}

train_once <- function(Rmodel, Rhistory, Rphi, logger) {
    invisible(.Call('BWPMF_train_once', PACKAGE = 'BWPMF', Rmodel, Rhistory, Rphi, logger))
}

pmf_logloss <- function(Rmodel, Rhistory) {
    .Call('BWPMF_pmf_logloss', PACKAGE = 'BWPMF', Rmodel, Rhistory)
}

